const bukkenData = [
  {
    "station": "堀切菖蒲園",
    "line": "京成本線",
    "title": "堀切3丁目貸住宅",
    "rent": "18万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.2,
    "deposit": "18万円",
    "gratuity": "18万円",
    "madori": "4LDK",
    "menseki": "95.47m2",
    "station_walk": "京成本線/堀切菖蒲園駅 歩6分 / 京成本線/お花茶屋駅 歩11分 / 東武伊勢崎線/堀切駅 歩23分",
    "address": "東京都葛飾区堀切３",
    "age_floor": "築17年 地上3階建",
    "url": "https://suumo.jp/chintai/jnc_000107596564/?bc=100523849000",
    "walk_min": 6,
    "train_min": 25,
    "door_to_door": 43,
    "total_walk_min": 7,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "京成本線,東京メトロ千代田線",
    "route_summary": "堀切菖蒲園→町屋(京成線)→町屋(東京メトロ)→大手町(東京都)",
    "lat": 35.7469202,
    "lng": 139.8263877,
    "is_new": false
  },
  {
    "station": "京成小岩",
    "line": "京成本線",
    "title": "北小岩5丁目貸家",
    "rent": "15万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "-",
    "self_pay": 3.0,
    "deposit": "15万円",
    "gratuity": "15万円",
    "madori": "3DK",
    "menseki": "106.13m2",
    "station_walk": "京成本線/京成小岩駅 歩9分 / ＪＲ総武線/小岩駅 歩18分 / 京成本線/江戸川駅 歩10分",
    "address": "東京都江戸川区北小岩５",
    "age_floor": "築28年 地上3階建",
    "url": "https://suumo.jp/chintai/jnc_000094793446/?bc=100522697545",
    "walk_min": 9,
    "train_min": 29,
    "door_to_door": 54,
    "total_walk_min": 10,
    "transfers": 2,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "京成本線,京成本線特急,東京メトロ半蔵門線",
    "route_summary": "京成小岩→京成高砂→押上→大手町(東京都)",
    "lat": 35.7423294,
    "lng": 139.8834675,
    "is_new": false
  },
  {
    "station": "東伏見",
    "line": "西武新宿線",
    "title": "西東京市富士町戸建",
    "rent": "18万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.2,
    "deposit": "36万円",
    "gratuity": "18万円",
    "madori": "4LDK",
    "menseki": "100.44m2",
    "station_walk": "西武新宿線/東伏見駅 歩7分 / 西武新宿線/武蔵関駅 歩14分 / 西武新宿線/西武柳沢駅 歩23分",
    "address": "東京都西東京市富士町４",
    "age_floor": "築26年 地上2階建",
    "url": "https://suumo.jp/chintai/jnc_000106200191/?bc=100499845900",
    "walk_min": 7,
    "train_min": 34,
    "door_to_door": 59,
    "total_walk_min": 8,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "西武新宿線準急,東京メトロ東西線",
    "route_summary": "東伏見→高田馬場→大手町(東京都)",
    "lat": 35.7287024,
    "lng": 139.5642364,
    "is_new": false
  },
  {
    "station": "柴又",
    "line": "京成金町線",
    "title": "柴又１丁目戸建て",
    "rent": "18万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.2,
    "deposit": "18万円",
    "gratuity": "18万円",
    "madori": "4DK",
    "menseki": "115.93m2",
    "station_walk": "京成金町線/柴又駅 歩4分 / 京成本線/京成高砂駅 歩11分 / ＪＲ常磐線/金町駅 歩20分",
    "address": "東京都葛飾区柴又１",
    "age_floor": "築29年 地上2階建",
    "url": "https://suumo.jp/chintai/jnc_000108966656/?bc=100508040324",
    "walk_min": 4,
    "train_min": 33,
    "door_to_door": 50,
    "total_walk_min": 5,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "京成金町線,ＪＲ常磐線",
    "route_summary": "柴又→京成金町→金町(東京都)→大手町(東京都)",
    "lat": 35.7563461,
    "lng": 139.8752164,
    "is_new": false
  },
  {
    "station": "登戸",
    "line": "小田急線",
    "title": "登戸貸家",
    "rent": "18万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.2,
    "deposit": "36万円",
    "gratuity": "18万円",
    "madori": "4DK",
    "menseki": "82.79m2",
    "station_walk": "小田急線/登戸駅 歩7分 / 小田急線/向ヶ丘遊園駅 歩9分 / ＪＲ南武線/中野島駅 歩19分",
    "address": "神奈川県川崎市多摩区登戸",
    "age_floor": "築28年 地上3階建",
    "url": "https://suumo.jp/chintai/jnc_000107581032/?bc=100509875371",
    "walk_min": 7,
    "train_min": 33,
    "door_to_door": 46,
    "total_walk_min": 8,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "小田急小田原線快速急行,東京メトロ千代田線",
    "route_summary": "登戸→代々木上原→大手町(東京都)",
    "lat": 35.6211127,
    "lng": 139.5695457,
    "is_new": false
  },
  {
    "station": "朝霞",
    "line": "東武東上線",
    "title": "朝霞貸家",
    "rent": "17.8万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.000000000000001,
    "deposit": "35.6万円",
    "gratuity": "17.8万円",
    "madori": "3SLDK",
    "menseki": "111.36m2",
    "station_walk": "東武東上線/朝霞駅 歩8分 / 東武東上線/和光市駅 歩16分 / ＪＲ武蔵野線/北朝霞駅 歩44分",
    "address": "埼玉県朝霞市仲町２",
    "age_floor": "築30年 3階建",
    "url": "https://suumo.jp/chintai/jnc_000102323498/?bc=100523976891",
    "walk_min": 8,
    "train_min": 37,
    "door_to_door": 58,
    "total_walk_min": 10,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 2,
    "lines_used": "東武東上線急行,東京メトロ丸ノ内線",
    "route_summary": "朝霞→池袋→大手町(東京都)",
    "lat": 35.79703,
    "lng": 139.6002238,
    "is_new": true
  },
  {
    "station": "鳩ヶ谷",
    "line": "埼玉高速鉄道",
    "title": "鳩ヶ谷本町戸建",
    "rent": "15.3万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 3.0600000000000005,
    "deposit": "30.6万円",
    "gratuity": "30.6万円",
    "madori": "4LDK",
    "menseki": "94.19m2",
    "station_walk": "埼玉高速鉄道/鳩ヶ谷駅 歩9分 / 埼玉高速鉄道/新井宿駅 歩25分 / 埼玉高速鉄道/南鳩ヶ谷駅 歩26分",
    "address": "埼玉県川口市鳩ヶ谷本町４",
    "age_floor": "築29年 2階建",
    "url": "https://suumo.jp/chintai/jnc_000108287102/?bc=100493849572",
    "walk_min": 9,
    "train_min": 35,
    "door_to_door": 59,
    "total_walk_min": 11,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 2,
    "lines_used": "埼玉高速鉄道,東京メトロ丸ノ内線",
    "route_summary": "鳩ケ谷→後楽園→大手町(東京都)",
    "lat": 35.8314948,
    "lng": 139.7366118,
    "is_new": false
  },
  {
    "station": "新井宿",
    "line": "埼玉高速鉄道",
    "title": "新井宿戸建住宅",
    "rent": "16.5万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 3.7,
    "deposit": "-",
    "gratuity": "16.5万円",
    "madori": "4LDK",
    "menseki": "94.4m2",
    "station_walk": "埼玉高速鉄道/新井宿駅 歩5分 /  / ",
    "address": "埼玉県川口市大字赤山",
    "age_floor": "築23年 地上2階建",
    "url": "https://suumo.jp/chintai/jnc_000109205365/?bc=100384775780",
    "walk_min": 5,
    "train_min": 38,
    "door_to_door": 58,
    "total_walk_min": 7,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 2,
    "lines_used": "埼玉高速鉄道,東京メトロ丸ノ内線",
    "route_summary": "新井宿→後楽園→大手町(東京都)",
    "lat": 35.8429473,
    "lng": 139.738258,
    "is_new": false
  },
  {
    "station": "川口元郷",
    "line": "埼玉高速鉄道",
    "title": "川口元郷１丁目戸建",
    "rent": "18万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.2,
    "deposit": "18万円",
    "gratuity": "18万円",
    "madori": "2SLDK",
    "menseki": "88.68m2",
    "station_walk": "埼玉高速鉄道/川口元郷駅 歩3分 / ＪＲ京浜東北線/川口駅 歩19分 / ",
    "address": "埼玉県川口市元郷１",
    "age_floor": "築9年 地上3階建",
    "url": "https://suumo.jp/chintai/jnc_000109422440/?bc=100512843855",
    "walk_min": 3,
    "train_min": 30,
    "door_to_door": 38,
    "total_walk_min": 4,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "埼玉高速鉄道",
    "route_summary": "川口元郷→大手町",
    "lat": 35.8006371,
    "lng": 139.7305528,
    "is_new": false
  },
  {
    "station": "新八柱",
    "line": "京成松戸線",
    "title": "タウン48　A",
    "rent": "17万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 4.2,
    "deposit": "17万円",
    "gratuity": "-",
    "madori": "3LDK",
    "menseki": "82.62m2",
    "station_walk": "京成松戸線/八柱駅 歩10分 / ＪＲ武蔵野線/新八柱駅 歩10分 / 京成松戸線/みのり台駅 歩9分",
    "address": "千葉県松戸市稔台１",
    "age_floor": "築2年 地上2階建",
    "url": "https://suumo.jp/chintai/jnc_000109288821/?bc=100522828174",
    "walk_min": 10,
    "train_min": 30,
    "door_to_door": 45,
    "total_walk_min": 11,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "京成松戸線",
    "route_summary": "新八柱→大手町",
    "lat": 35.7919514,
    "lng": 139.9383839,
    "is_new": false
  },
  {
    "station": "松戸新田",
    "line": "京成松戸線",
    "title": "松戸新田貸戸建て",
    "rent": "17.5万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 4.7,
    "deposit": "17.5万円",
    "gratuity": "-",
    "madori": "3LDK",
    "menseki": "85.5m2",
    "station_walk": "京成松戸線/松戸新田駅 歩2分 / 京成松戸線/みのり台駅 歩7分 / 京成松戸線/八柱駅 歩16分",
    "address": "千葉県松戸市松戸新田",
    "age_floor": "築3年 2階建",
    "url": "https://suumo.jp/chintai/jnc_000087076900/?bc=100357816115",
    "walk_min": 2,
    "train_min": 39,
    "door_to_door": 53,
    "total_walk_min": 3,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "京成松戸線,ＪＲ常磐線",
    "route_summary": "松戸新田→松戸→大手町(東京都)",
    "lat": 35.7906265,
    "lng": 139.9226166,
    "is_new": false
  },
  {
    "station": "松戸新田",
    "line": "京成松戸線",
    "title": "松戸新田貸戸建て",
    "rent": "18万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.2,
    "deposit": "18万円",
    "gratuity": "18万円",
    "madori": "3LDK",
    "menseki": "85.5m2",
    "station_walk": "京成松戸線/松戸新田駅 歩2分 / 京成松戸線/みのり台駅 歩7分 / 京成松戸線/八柱駅 歩16分",
    "address": "千葉県松戸市松戸新田",
    "age_floor": "築3年 2階建",
    "url": "https://suumo.jp/chintai/jnc_000107625556/?bc=100510201810",
    "walk_min": 2,
    "train_min": 39,
    "door_to_door": 53,
    "total_walk_min": 3,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "京成松戸線,ＪＲ常磐線",
    "route_summary": "松戸新田→松戸→大手町(東京都)",
    "lat": 35.7906265,
    "lng": 139.9226166,
    "is_new": false
  },
  {
    "station": "松戸新田",
    "line": "京成松戸線",
    "title": "松戸新田貸戸建て",
    "rent": "18万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.2,
    "deposit": "18万円",
    "gratuity": "-",
    "madori": "3LDK",
    "menseki": "85.15m2",
    "station_walk": "京成松戸線/松戸新田駅 歩2分 / 京成松戸線/みのり台駅 歩7分 / 京成松戸線/八柱駅 歩16分",
    "address": "千葉県松戸市松戸新田",
    "age_floor": "築3年 2階建",
    "url": "https://suumo.jp/chintai/jnc_000108673234/?bc=100510956654",
    "walk_min": 2,
    "train_min": 39,
    "door_to_door": 53,
    "total_walk_min": 3,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "京成松戸線,ＪＲ常磐線",
    "route_summary": "松戸新田→松戸→大手町(東京都)",
    "lat": 35.7906265,
    "lng": 139.9226166,
    "is_new": false
  },
  {
    "station": "北小金",
    "line": "ＪＲ常磐線",
    "title": "大金平戸建",
    "rent": "13万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 2.6,
    "deposit": "26万円",
    "gratuity": "13万円",
    "madori": "4DK",
    "menseki": "82.53m2",
    "station_walk": "ＪＲ常磐線/北小金駅 歩5分 / 流鉄流山線/小金城趾駅 歩17分 / ＪＲ常磐線/新松戸駅 歩19分",
    "address": "千葉県松戸市大金平１",
    "age_floor": "築29年 地上3階建",
    "url": "https://suumo.jp/chintai/jnc_000108144318/?bc=100523136213",
    "walk_min": 5,
    "train_min": 44,
    "door_to_door": 54,
    "total_walk_min": 6,
    "transfers": 0,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "ＪＲ常磐線",
    "route_summary": "北小金→大手町(東京都)",
    "lat": 35.8330516,
    "lng": 139.9315725,
    "is_new": false
  },
  {
    "station": "北小金",
    "line": "ＪＲ常磐線",
    "title": "井坂邸",
    "rent": "17万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 4.2,
    "deposit": "25.5万円",
    "gratuity": "17万円",
    "madori": "4LDK",
    "menseki": "99.72m2",
    "station_walk": "ＪＲ常磐線/北小金駅 歩10分 / 流鉄流山線/小金城趾駅 歩22分 / ＪＲ常磐線/新松戸駅 歩27分",
    "address": "千葉県松戸市東平賀",
    "age_floor": "築9年 地上2階建",
    "url": "https://suumo.jp/chintai/jnc_000108746283/?bc=100521801875",
    "walk_min": 10,
    "train_min": 44,
    "door_to_door": 59,
    "total_walk_min": 11,
    "transfers": 0,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "ＪＲ常磐線",
    "route_summary": "北小金→大手町(東京都)",
    "lat": 35.8330516,
    "lng": 139.9315725,
    "is_new": false
  },
  {
    "station": "南流山",
    "line": "つくばエクスプレス",
    "title": "南流山6丁目戸建A",
    "rent": "17.8万円",
    "admin": "-",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "付無料",
    "self_pay": 5.000000000000001,
    "deposit": "35.6万円",
    "gratuity": "35.6万円",
    "madori": "3LDK",
    "menseki": "86.45m2",
    "station_walk": "つくばエクスプレス/南流山駅 歩7分 / ＪＲ武蔵野線/南流山駅 歩7分 / 流鉄流山線/鰭ヶ崎駅 歩19分",
    "address": "千葉県流山市南流山６",
    "age_floor": "築7年 地上2階建",
    "url": "https://suumo.jp/chintai/jnc_000109313346/?bc=100523019537",
    "walk_min": 7,
    "train_min": 35,
    "door_to_door": 56,
    "total_walk_min": 8,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "つくばエクスプレス区間快速,東京メトロ千代田線",
    "route_summary": "南流山→北千住→大手町(東京都)",
    "lat": 35.8389226,
    "lng": 139.904336,
    "is_new": true
  },
  {
    "station": "南流山",
    "line": "つくばエクスプレス",
    "title": "ボー・リバージュ",
    "rent": "14.9万円",
    "admin": "8000円",
    "parking_fee": 0.0,
    "parking_dist": 0,
    "parking_text": "-",
    "self_pay": 3.1400000000000006,
    "deposit": "-",
    "gratuity": "7.45万円",
    "madori": "3LDK",
    "menseki": "80.14m2",
    "station_walk": "つくばエクスプレス/南流山駅 歩7分 / ＪＲ武蔵野線/南流山駅 歩7分 / 流鉄流山線/鰭ヶ崎駅 歩15分",
    "address": "千葉県流山市南流山２",
    "age_floor": "築12年 地上3階建",
    "url": "https://suumo.jp/chintai/jnc_000090210334/?bc=100494215803",
    "walk_min": 7,
    "train_min": 35,
    "door_to_door": 56,
    "total_walk_min": 8,
    "transfers": 1,
    "arrival_station": "大手町(東京都)",
    "arrival_walk_min": 1,
    "lines_used": "つくばエクスプレス区間快速,東京メトロ千代田線",
    "route_summary": "南流山→北千住→大手町(東京都)",
    "lat": 35.8389226,
    "lng": 139.904336,
    "is_new": true
  }
];